---
include:
  - template: 'Jobs/Code-Intelligence.gitlab-ci.yml'
  - template: 'Security/Container-Scanning.gitlab-ci.yml'
  - template: 'Security/Dependency-Scanning.gitlab-ci.yml'
  - template: 'Security/License-Scanning.gitlab-ci.yml'
  - template: 'Security/SAST.gitlab-ci.yml'
  - template: 'Security/Secret-Detection.gitlab-ci.yml'
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $IMAGE || true
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG || true
    - docker pull $CI_REGISTRY_IMAGE/main || true
    - docker pull $CI_REGISTRY_IMAGE || true
    - docker build -t $IMAGE .
    - docker push $IMAGE

container_scanning:
  variables:
    GIT_STRATEGY: fetch
    DOCKERFILE_PATH: ./Dockerfile

# Use container image to build firmware
# Keep firmware as artifact
